/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as StartHereRouteImport } from './routes/start-here'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as LrnInboxRouteImport } from './routes/lrn-inbox'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LetsConnectRouteImport } from './routes/lets-connect'
import { Route as LeadNurtureRouteImport } from './routes/lead-nurture'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as AreasServedRouteImport } from './routes/areas-served'
import { Route as AgentPreviewRouteImport } from './routes/agent-preview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const StartHereRoute = StartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const LrnInboxRoute = LrnInboxRouteImport.update({
  id: '/lrn-inbox',
  path: '/lrn-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LetsConnectRoute = LetsConnectRouteImport.update({
  id: '/lets-connect',
  path: '/lets-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadNurtureRoute = LeadNurtureRouteImport.update({
  id: '/lead-nurture',
  path: '/lead-nurture',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasServedRoute = AreasServedRouteImport.update({
  id: '/areas-served',
  path: '/areas-served',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPreviewRoute = AgentPreviewRouteImport.update({
  id: '/agent-preview',
  path: '/agent-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-preview': typeof AgentPreviewRoute
  '/areas-served': typeof AreasServedRoute
  '/buyer': typeof BuyerRoute
  '/faq': typeof FaqRoute
  '/lead-nurture': typeof LeadNurtureRoute
  '/lets-connect': typeof LetsConnectRoute
  '/listings': typeof ListingsRoute
  '/lrn-inbox': typeof LrnInboxRoute
  '/question': typeof QuestionRoute
  '/seller': typeof SellerRoute
  '/start-here': typeof StartHereRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-preview': typeof AgentPreviewRoute
  '/areas-served': typeof AreasServedRoute
  '/buyer': typeof BuyerRoute
  '/faq': typeof FaqRoute
  '/lead-nurture': typeof LeadNurtureRoute
  '/lets-connect': typeof LetsConnectRoute
  '/listings': typeof ListingsRoute
  '/lrn-inbox': typeof LrnInboxRoute
  '/question': typeof QuestionRoute
  '/seller': typeof SellerRoute
  '/start-here': typeof StartHereRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-preview': typeof AgentPreviewRoute
  '/areas-served': typeof AreasServedRoute
  '/buyer': typeof BuyerRoute
  '/faq': typeof FaqRoute
  '/lead-nurture': typeof LeadNurtureRoute
  '/lets-connect': typeof LetsConnectRoute
  '/listings': typeof ListingsRoute
  '/lrn-inbox': typeof LrnInboxRoute
  '/question': typeof QuestionRoute
  '/seller': typeof SellerRoute
  '/start-here': typeof StartHereRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent-preview'
    | '/areas-served'
    | '/buyer'
    | '/faq'
    | '/lead-nurture'
    | '/lets-connect'
    | '/listings'
    | '/lrn-inbox'
    | '/question'
    | '/seller'
    | '/start-here'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent-preview'
    | '/areas-served'
    | '/buyer'
    | '/faq'
    | '/lead-nurture'
    | '/lets-connect'
    | '/listings'
    | '/lrn-inbox'
    | '/question'
    | '/seller'
    | '/start-here'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent-preview'
    | '/areas-served'
    | '/buyer'
    | '/faq'
    | '/lead-nurture'
    | '/lets-connect'
    | '/listings'
    | '/lrn-inbox'
    | '/question'
    | '/seller'
    | '/start-here'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentPreviewRoute: typeof AgentPreviewRoute
  AreasServedRoute: typeof AreasServedRoute
  BuyerRoute: typeof BuyerRoute
  FaqRoute: typeof FaqRoute
  LeadNurtureRoute: typeof LeadNurtureRoute
  LetsConnectRoute: typeof LetsConnectRoute
  ListingsRoute: typeof ListingsRoute
  LrnInboxRoute: typeof LrnInboxRoute
  QuestionRoute: typeof QuestionRoute
  SellerRoute: typeof SellerRoute
  StartHereRoute: typeof StartHereRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-here': {
      id: '/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof StartHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lrn-inbox': {
      id: '/lrn-inbox'
      path: '/lrn-inbox'
      fullPath: '/lrn-inbox'
      preLoaderRoute: typeof LrnInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lets-connect': {
      id: '/lets-connect'
      path: '/lets-connect'
      fullPath: '/lets-connect'
      preLoaderRoute: typeof LetsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-nurture': {
      id: '/lead-nurture'
      path: '/lead-nurture'
      fullPath: '/lead-nurture'
      preLoaderRoute: typeof LeadNurtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-served': {
      id: '/areas-served'
      path: '/areas-served'
      fullPath: '/areas-served'
      preLoaderRoute: typeof AreasServedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-preview': {
      id: '/agent-preview'
      path: '/agent-preview'
      fullPath: '/agent-preview'
      preLoaderRoute: typeof AgentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentPreviewRoute: AgentPreviewRoute,
  AreasServedRoute: AreasServedRoute,
  BuyerRoute: BuyerRoute,
  FaqRoute: FaqRoute,
  LeadNurtureRoute: LeadNurtureRoute,
  LetsConnectRoute: LetsConnectRoute,
  ListingsRoute: ListingsRoute,
  LrnInboxRoute: LrnInboxRoute,
  QuestionRoute: QuestionRoute,
  SellerRoute: SellerRoute,
  StartHereRoute: StartHereRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
